
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


source ~/.profile


alias ls='ls -aFhlG'
alias ..='cd ..'
alias cd..='cd ..'
alias ...='cd ../..'
alias subl='open -a "Sublime Text"'
alias slt='open -a "Sublime Text"'

EDITOR='nano'; export EDITOR

alias hosts='sudo $EDITOR /etc/hosts'
alias vagloc='cd ~/Server/localhost.dev/ && open ./ && vagrant up'

# cd into whatever is the forefront Finder window.
cdf() { # short for cdfinder
  cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"
}

# Recursively delete `.DS_Store` files
alias cleanup="find . -name '*.DS_Store' -type f -ls -delete"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""


#
# Run after changing this file: source ~/.bash_profile
#
